// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WriteBulkData.Model.Mapping
{
    using WriteBulkData.Model;

    // Producto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class ProductoMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Producto>
    {
        public ProductoMap()
            : this("dbo")
        {
        }

        public ProductoMap(string schema)
        {
            ToTable("Producto", schema);
            HasKey(x => x.CodigoProducto);

            Property(x => x.CodigoProducto).HasColumnName(@"CodigoProducto").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Descripcion).HasColumnName(@"Descripcion").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.PrecioVenta).HasColumnName(@"PrecioVenta").HasColumnType("decimal").IsRequired().HasPrecision(18,0);
            Property(x => x.Existencia).HasColumnName(@"Existencia").HasColumnType("int").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
