// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WriteBulkData.Model
{
    using WriteBulkData.Model.Mapping;

    // EncabezadoFactura
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class EncabezadoFactura
    {
        public int NumeroFactura { get; set; } // NumeroFactura (Primary key)
        public string Serie { get; set; } // Serie (Primary key) (length: 1)
        public decimal Monto { get; set; } // Monto
        public System.DateTime Fecha { get; set; } // Fecha
        public string Nit { get; set; } // Nit (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child DetalleFacturas where [DetalleFactura].([NumeroFactura], [Serie]) point to this entity (FK_DetalleFactura_EncabezadoFactura)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DetalleFactura> DetalleFacturas { get; set; } = new System.Collections.Generic.HashSet<DetalleFactura>(); // DetalleFactura.FK_DetalleFactura_EncabezadoFactura
    }

}
// </auto-generated>
