// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WriteBulkData.Model
{
    using WriteBulkData.Model.Mapping;

    // Producto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Producto
    {
        public int CodigoProducto { get; set; } // CodigoProducto (Primary key)
        public string Descripcion { get; set; } // Descripcion (length: 50)
        public decimal PrecioVenta { get; set; } // PrecioVenta
        public int Existencia { get; set; } // Existencia

        // Reverse navigation

        /// <summary>
        /// Child DetalleFacturas where [DetalleFactura].[CodigoProducto] point to this entity (FK_DetalleFactura_Producto)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DetalleFactura> DetalleFacturas { get; set; } = new System.Collections.Generic.HashSet<DetalleFactura>(); // DetalleFactura.FK_DetalleFactura_Producto
    }

}
// </auto-generated>
